# Generated by Django 3.2.9 on 2021-11-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst', '0002_auto_20211119_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUsers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=150, null=True)),
                ('email', models.CharField(default='', max_length=254, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('password', models.CharField(default='', max_length=128, null=True)),
            ],
            options={
                'db_table': 'auth_users',
            },
        ),
    ]
